#include "pit.h"
#include "systemcalls.h"

int32_t ticks = 0;

/*
 * pit_init
 *   DESCRIPTION: Initializes the Programmable Interval Timer (PIT) for periodic interrupts.
 *   INPUTS: None.
 *   OUTPUTS: Initializes the PIT.
 *   RETURN VALUE: None.
 *   SIDE EFFECTS: Modifies PIT configuration.
 */

void pit_init(){

    cli();
    outb(0x36, 0x43); // set channel 0, lobyte/hibyte, square wave oscillator

    outb(200, 0x40);  // Low byte
	outb(0, 0x40);	// High byte

    enable_irq(0); // enable PIC IRQ 0 for PIT interrupts
    sti();

    // set a file ops table?
}
uint32_t pit_get_ticks() { return ticks; }
/*
 * pit_intr_handler
 *   DESCRIPTION: Handles the interrupt generated by the PIT.
 *   INPUTS: None.
 *   OUTPUTS: Updates the system timer and performs necessary actions.
 *   RETURN VALUE: None.
 *   SIDE EFFECTS: Modifies system state.
 */

void pit_intr_handler(){
    // cli();

    // outb(0xC2, 0x43); // Bits 7 and 6 set for Read Back command
    // inb(0x40); // Read the status byte from channel 0

    ticks++;
    // schedule();
    if (ticks % 10 == 0)
        // printf("tick\n");
        scheduler();
    // printf("ticks: %d\n", ticks);

    // the TRICKY TRANSITION

    // sti();
    send_eoi(0);
}